#!/usr/bin/env python3
"""
Secure Boot & sbctl management engine.
Handles checking sbctl status, generating enrollment commands, and verifying EFI signatures.
"""

import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Dict, Any, List, Tuple, Optional

BOOT_DIR = Path("/boot")
EFI_DIR = Path("/boot/EFI")


def check_sbctl_installed() -> bool:
    """Checks whether sbctl binary is installed on system."""
    return shutil.which("sbctl") is not None


def get_sbctl_status() -> Dict[str, Any]:
    """
    Runs sbctl status to get cryptographic status.
    Returns parsed dictionary or fallback based on /sys/firmware/efi.
    """
    if not check_sbctl_installed():
        return {
            "installed": False,
            "setup_mode": False,
            "secure_boot": False,
            "enrolled": False,
            "keys_created": False,
            "raw": "sbctl is not installed."
        }

    try:
        res = subprocess.run(["sbctl", "status", "--json"], capture_output=True, text=True, check=False)
        if res.returncode == 0:
            data = json.loads(res.stdout)
            data["installed"] = True
            return data
    except Exception:
        pass

    # Fallback to plain sbctl status text parsing
    try:
        res = subprocess.run(["sbctl", "status"], capture_output=True, text=True, check=False)
        stdout = res.stdout.lower()
        return {
            "installed": True,
            "setup_mode": "setup mode: enabled" in stdout,
            "secure_boot": "secure boot: enabled" in stdout,
            "enrolled": "vendor keys: custom" in stdout or "keys enrolled: yes" in stdout,
            "raw": res.stdout.strip()
        }
    except Exception as e:
        return {
            "installed": True,
            "error": str(e)
        }


def get_signable_files() -> List[str]:
    """
    Scans /boot for EFI binaries that require signing for Omarchy + Limine
    to boot under Secure Boot. Uses sudo find so it works even when /boot
    is mounted with fmask=0077 (unreadable by non-root users).
    Falls back to a hardcoded baseline if sudo find is unavailable.
    """
    baseline = [
        "/boot/EFI/BOOT/BOOTX64.EFI",
        "/boot/EFI/LIMINE/LIMINE_X64.EFI",
    ]

    try:
        res = subprocess.run(
            ["sudo", "-n", "find", "/boot", "-name", "*.efi", "-type", "f"],
            capture_output=True, text=True, check=False, timeout=5
        )
        if res.returncode == 0 and res.stdout.strip():
            found = [l.strip() for l in res.stdout.strip().splitlines() if l.strip()]
            # Exclude snapshot history files — handled separately
            live = [f for f in found if "limine_history" not in f]
            return sorted(set(baseline + live))
    except Exception:
        pass

    # Non-root fallback: only return what we know for certain
    return sorted(baseline)


def get_signable_snapshot_files() -> List[str]:
    """
    Returns snapshot kernel history EFIs from limine_history directories.
    These are immutable copies that must be signed individually (no -s flag).
    """
    try:
        res = subprocess.run(
            ["sudo", "-n", "find", "/boot", "-path", "*/limine_history/*", "-type", "f"],
            capture_output=True, text=True, check=False, timeout=5
        )
        if res.returncode == 0 and res.stdout.strip():
            return sorted(l.strip() for l in res.stdout.strip().splitlines() if l.strip())
    except Exception:
        pass
    return []


def generate_setup_commands() -> List[str]:
    """
    Returns the exact sequence of shell commands to set up sbctl,
    enroll keys with Microsoft CA support (-m), and sign all boot files.

    Kernel EFI paths are enumerated at call-time via sudo find so that
    the glob never silently skips files on fmask=0077-mounted /boot partitions.
    Snapshot history files are signed individually without -s (they are
    immutable copies that will never be regenerated by a pacman hook).
    """
    cmds = [
        "sudo pacman -S --needed --noconfirm sbctl",
        "sudo sbctl create-keys",
        "sudo sbctl enroll-keys -m",
    ]

    # Sign live EFI files and register with sbctl (-s) for auto-resign on updates
    for path in get_signable_files():
        cmds.append(f"sudo sbctl sign -s {path}")

    # Sign immutable snapshot history kernels (no -s — they won't be regenerated)
    snapshots = get_signable_snapshot_files()
    if snapshots:
        for path in snapshots:
            cmds.append(f"sudo sbctl sign {path}")

    cmds.append("sudo sbctl verify")
    return cmds


def verify_signatures() -> Tuple[bool, str]:
    """Runs sbctl verify to confirm that all required EFI binaries are signed."""
    if not check_sbctl_installed():
        return False, "sbctl is not installed"

    try:
        res = subprocess.run(["sbctl", "verify"], capture_output=True, text=True, check=False)
        is_ok = (res.returncode == 0)
        return is_ok, res.stdout.strip() or res.stderr.strip()
    except Exception as e:
        return False, str(e)


if __name__ == "__main__":
    print(f"sbctl installed: {check_sbctl_installed()}")
    print(f"Status: {json.dumps(get_sbctl_status(), indent=2)}")
    print("Signable live files:")
    for f in get_signable_files():
        print(f"  - {f}")
    print("Signable snapshot files:")
    for f in get_signable_snapshot_files():
        print(f"  - {f}")
    print("Generated setup commands:")
    for c in generate_setup_commands():
        print(f"  {c}")
